name: FastAPI CI Test

on:
#  push:
#    branches: [ 'main', 'feature/**']
#    tags: [ 'v*']
   pull_request:
     branches: [ 'main' ]

jobs:

  code-quality:
    name: Check coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Check code formatting
        run: poetry run poe black-check